# Generated by Django 5.0.7 on 2024-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='desc',
            new_name='conf',
        ),
        migrations.AddField(
            model_name='signin',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
