# Generated by Django 5.0.7 on 2024-11-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='disc',
            new_name='cdisc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='csubject',
        ),
    ]
